name: publish

on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'release ')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}

      - run: git config --global user.name "${{ secrets.USER_NAME }}"
      - run: git config --global user.email "${{ secrets.USER_EMAIL }}"
      - run: npm version patch -m "release v%s"
      - run: git push origin main

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build
        run: pnpm install && pnpm build

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
